spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/ymgjrhch?createDatabaseIfNotExist=true&useSSL=true
    username: ymgjrhch
    password: lTAArmbdJbm3KnlRb5V3ADaQsia8cKsh
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql