spring:
  application:
    name: user-service
  profiles:
    active: dev
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: false
    enabled: true
    locations: classpath:/db/migration
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 3000