CREATE TABLE users(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    specific_id VARCHAR(36) NOT NULL,
    name VARCHAR(50) NOT NULL,
    age INTEGER NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    sex VARCHAR(50) NOT NULL
);